---
- name: configure nginx for it355
  copy: src=it355.conf dest=/etc/nginx/sites-available/it355.conf

- name: enable it355
  file: src=/etc/nginx/sites-available/it355.conf dest=/etc/nginx/sites-enabled/it355.conf state=link
  notify:
    - restart nginx
