---
- name: configure nginx for db-rest
  copy: src=db-rest.conf dest=/etc/nginx/sites-available/db-rest.conf

- name: enable db-rest
  file: src=/etc/nginx/sites-available/db-rest.conf dest=/etc/nginx/sites-enabled/db-rest.conf state=link
  notify:
    - restart nginx
